import Head from 'next/head'

const HomePage = () => {
    return (
        <>
            <Head>
                <title>Next.js app with route loading</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <div className={'container'}>main page</div>
            </main>
        </>
    )
}
export default HomePage;
